CREATE DATABASE bdLojaCT
GO
USE bdLojaCT
CREATE TABLE tbCAIXA( 
CODIGO   INT   PRIMARY KEY   IDENTITY(1,1)
, DATACAIXA   DATETIME
, SALDO_INICIAL MONEY
, SALDO_FINAL  MONEY
)
GO
USE bdLojaCT

INSERT INTO tbCAIXA
VALUES (CONVERT(DATETIME, CONVERT(VARCHAR(10), GETDATE(), 103)), 100, 100)
GO
 SELECT * FROM tbCAIXA
 CREATE TABLE tbVENDAS( 
 DATAVENDA DATETIME
 , CODIGO INT
 , VALOR MONEY
 )
 GO
 SELECT * FROM tbVENDAS
  -------------criação do Trigger -----------------------
  CREATE TRIGGER tgAtualizaCaixa
  ON tbVendas AFTER INSERT
  AS 
	DECLARE @valorVenda MONEY, @data DATETIME 

	SET @valorVenda = (SELECT VALOR FROM inserted) 
	SET @data = (SELECT CONVERT(VARCHAR(10),DATAVENDA, 103) FROM inserted) 
	
	UPDATE tbCAIXA  
	SET SALDO_FINAL = SALDO_FINAL + @valorVenda   
		WHERE DATACAIXA = @data PRINT ('Caixa atualizado com sucesso!')
--------testes --------------
SELECT * FROM tbCAIXA
SELECT * FROm tbVENDAS
INSERT tbVENDAS(DATAVENDA, CODIGO, VALOR)
VALUES ('02/10/2024', 1, 1430.00) 